### PR TITLE
Add code coverage report uploads to codecove.io

### PR DESCRIPTION
**Pull request by alexskr**

### CODE REVIEW

**Comment by syphax-bouazzouni** [comment]
Hi @alexskr ,

did you fix the [tests issues](https://github.com/ontoportal-lirmm/goo/issues/9) ?

**Comment by alexskr** [comment]
Hi @syphax-bouazzouni,
@stdotjohn made some progress so unit tests now pass

**Comment by syphax-bouazzouni** [comment]
> Hi @syphax-bouazzouni, @stdotjohn made some progress so unit tests now pass

Ah ok great,
thanks @stdotjohn and @alexskr

**Comment by alexskr** [comment]
We still have a bunch of disabled tests but at least there is some progress

**Comment by ncbo-deployer** [comment]
Four tests are skipped.  The slice_loading_size logic makes it look four times bigger (for 16 skipped tests) but is irrelevant. The tests have the following explanations:

  1.  TestChunkWrite.rb#test_reentrant_queries – This is not a good test and probably can’t be fixed.  It runs up against threading issues and currently fails because a “long” running thread is done too early.
  2.  TestCollection#test_inverse_on_collection – This test says “Not supported inverse on collection”
  3.  TestComplex::TestModelComplex#test_aggregate – This test involves transitive closure and doesn’t work as written. I will see if I can make it work with AllegroGraph as their reasoner supports the OWL construct of transitively closed properties.
  4.  TestReadOnly::TestReadOnlyWithStruct#test_embed_struct has the attached comment “not yet” and was not further investigated.

The last three tests will be re-evaluated on the switch to AllegroGraph.



-Timothy

From: bioontology-admin ***@***.***> on behalf of Alex Skrenchuk ***@***.***>
Date: Wednesday, November 16, 2022 at 11:33 PM
To: ncbo/goo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [bioontology-admin] [ncbo/goo] Add code coverage report uploads to codecove.io (PR #126)

We still have a bunch of disabled tests but at least there is some progress

**Comment by syphax-bouazzouni** [comment]
A remark, see https://github.com/ncbo/goo/commit/0e09816b121750b3bb875a5c24cb79865287fcf4#commitcomment-90304626
> Hi @stdotjohn ,
> 
> I agree with your problem discription "the classes constraint was not covered", but i don't think that disabling it is the fix (and may break the ontologies_linked_data models).
> 
> For information also, here the constrain `:class` for an attribute means it will be instanciate as a Class resource (owl:Class , not the ruby class)
> 
> This behavior is done the else state of the switch
> 
> https://github.com/ncbo/goo/blob/0e09816b121750b3bb875a5c24cb79865287fcf4/lib/goo/validators/enforce.rb#L98-L113
> 
> @mdorf can give a second review of this

**Pull request merged**
