### PR TITLE
Feature: implement new validators

### PR DESCRIPTION
**Pull request by syphax-bouazzouni**
### Prerequisites 

- https://github.com/ncbo/goo/pull/138

### Context
See https://github.com/agroportal/project-management/issues/393

### Changes

- Add instance proc validators (8b14505850613d3ad7176dc68a45370e618a761c)

Now we can call, model-specific validators.

For example, if a  model defines an instance method called `equal_to_10` that tests if a value is equal to `10`. 

Then we can reference it as a validator for an attribute, like so `attribute :age, enforce: [:equal_to_10]`, this will enforce the attribute `age` to be `10` (as implemented in the method `equal_to_10`)

- Add `distinct_of` validator (0be792585ee84614dad2ba2a4a5af697e7351f05)

```
p1 distinct_of p2 enforce: A p1 B ^ A p2 C -> B <> C
```
- Add `superior_equla_to`  validator (deed329490cb74a0e725c2fefc656062d69f8b50)

```
p1 superior_equla_to p2 enforce: A p1 B ^ A p2 C -> C <= B
```

- Add `email` validator , that enforce the string to be a valid email 

- Add `symmetric` validator (5164723b2d3e6b32312d8ee874df06ad881af09e)
```
p is symmetric enforce: A p B -> B p A
```

- Add `inverse_of` validator (d57a719692b70308a992e24d75d64f5ecdd6a602)
```
p1 inverse_of p2 enforce: A p1 B  -> B p2 A
```

### CODE REVIEW

**Comment by mdorf** [comment]
We are getting this error when running [ncbo/ontologies_linked_data](https://github.com/ncbo/ontologies_linked_data) unit tests:
```
	 2: from /Users/mdorf/dev/ncbo/goo/lib/goo/validators/validator.rb:94:in `empty_to_s?'
	 1: from /Users/mdorf/dev/ncbo/ontologies_linked_data/lib/ontologies_linked_data/models/users/user.rb:93:in `to_s'
/Users/mdorf/dev/ncbo/goo/lib/goo/base/settings/settings.rb:272:in `block in shape_attribute': Attribute `username` is not loaded for http://data.bioontology.org/users/tim. Loaded attributes: #<Set: {}>. (Goo::Base::AttributeNotLoaded)
rake aborted!
```
Is there another pull request inside ontologies_linked_data that we are missing?

**Comment by mdorf** [comment]
With the new validators in place, it appears that the "username" of the User object is automatically assumed to have been loaded, which is not always the case, hence these errors.  This errors out in multiple places in our test code.

**Comment by mdorf** [comment]
These types of errors would be almost impossible to detect unit after the code is merged and deployed. We should be more diligent about submitting pull requests that are not fully self contained (or at least without having the additional dependencies clearly documented in the PR).

**Comment by mdorf** [comment]
@syphax-bouazzouni, just wanted to check if you saw my original error report.  The code errors out at:
```
      def to_s
        self.username.to_s
      end
```
Adding this code fixes many of these errors, but not all:
```
      def to_s
        self.bring(:username) if self.bring?(:username)
        self.username.to_s
      end
```
Do you have a different fix to this? This issue prevents us from proceeding.

**Comment by syphax-bouazzouni** [comment]
Hi @mdorf ,

I did this PR, that fixed the failing test in ontologies-linked-data (https://github.com/ontoportal-lirmm/ontologies_linked_data/actions/runs/6042678133).

A better solution would be the function `empty_to_s?(object)`, like so 

```ruby 
   def empty_to_s?(object)
        begin 
           object && object.to_s&.strip.empty?
       rescue 
         return true
       end
  end

```

**Pull request merged**
